server:
  port: 9100
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
# set zipkin server
spring:
  zipkin:
    base-url: http://10.2.3.52:9411/
  sleuth:
    sampler:
      probability: 1.0

security:
  oauth2:
    client:
      clientId: comsumer-demo
      clientSecret: ${COMSUMER_SERVICE_PASSWORD}
      accessTokenUri: http://10.2.3.52:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

#spring:
#  rabbitmq:
#    host: 10.2.1.45
#    port: 5672
#    username: guest
#    password: guest
logging:
  level:
    root: INFO

#spring:
##  sleuth:
##    web:
##      client:
##        enabled: true
##    sampler:
##      percentage: 1.0
#  rabbitmq:
#    host: 10.2.1.45
#    port: 5672
#    username: guest
#    password: guest
#zipkin:
#  #内存方式配置，不需要
#  #base-url: http://localhost:9411
#  #日志发送队列类型
#  sender:
#    type: rabbit
#  #发送的队列名称，默认zipkin，正常情况不要修改因为zipkin-server默认监控队列也是zipkin
#  rabbitmq:
#    queue: zipkin
#  sleuth:
#    #统计收集百分比默认0.1，正式环境可不配置
#    sampler:
#      percentage: 1.0